### ISSUE TITLE
NO ipa ?

### ISSUE THREAD

**Issue by Passsword1234** [mineek/dirtycowapp#6]

**Comment by TheKing349** [comment]
Go to the “Actions” tab and click on the latest. At the very bottom, there are “Artifacts”, which is where the .ipa is

**Comment by Passsword1234** [comment]
> Go to the “Actions” tab and click on the latest. At the very bottom, there are “Artifacts”, which is where the .ipa is

I saw it but its just a text no link for ipa

**Comment by TheKing349** [comment]
> > Go to the “Actions” tab and click on the latest. At the very bottom, there are “Artifacts”, which is where the .ipa is
> 
> I saw it but its just a text no link for ipa

You have to click on the text, it won’t work unless you’re signed in. Just click on the test or the box thing to the left of it

**Comment by Passsword1234** [comment]
> > > Go to the “Actions” tab and click on the latest. At the very bottom, there are “Artifacts”, which is where the .ipa is
> 
> > 
> 
> > I saw it but its just a text no link for ipa
> 
> 
> 
> You have to click on the text, it won’t work unless you’re signed in. Just click on the test or the box thing to the left of it

Thanks man
